### ISSUE TITLE
golang on AWS Lambda

### ISSUE THREAD

**Issue by lion3ls** [pkosterman/aws-lambda-barcode-generator#1]
Hi there,

I think it would result in a simplier code using https://github.com/eawsy/aws-lambda-go-net which is based on https://github.com/eawsy/aws-lambda-go-shim.

I'm co-author of those libs and would be happy to help if needed on our gitter:
https://gitter.im/eawsy/bavardage

Nice job btw, keep continue hacking on lambda :+1:

**Comment by pkosterman** [comment]
Thanks for your feedback!

Taken a look at both your repo's - looks great. Will definitely give that a go next.
